### ISSUE TITLE
Mac version please?

### ISSUE THREAD

**Issue by pedsm** [jonathanballs/logmaster#2]

**Comment by jonathanballs** [comment]
Just assigned you to handle this. Get to work ;)

**Comment by pedsm** [comment]
Can we get a server/client architecture?

**Comment by pedsm** [comment]
Please re-open due to high user demand

**Comment by jonathanballs** [comment]
Hi - just implemented this now. The DFA (dankness first architecture) approach that logmaster has taken allows all features to be implemented within minutes. I will push later today.
